# RCam Default Configuration

application:
  output_directory: "./output" # Default directory for saving images and videos
  image_format: "jpg" # e.g., "jpg", "png"
  video_format: "mp4" # Container, e.g., "mp4", "mkv"
  video_codec: "h264" # e.g., "h264", "mjpeg", "copy" (to copy stream directly if supported)
  video_fps: 25.0 # Target recording FPS (float)
  video_duration_default_seconds: 300 # Default recording duration in seconds (integer)
  filename_timestamp_format: "%Yy%mm%dd%Hh%Mm%Ss" # strftime format string for filenames
  rtsp_transport: "tcp" # Preferred RTSP transport ("tcp" or "udp") - May be handled by OpenCV internally
  time_sync_tolerance_seconds: 5.0 # Tolerance for verify-time command (float)
  log_level: "info" # e.g., "error", "warn", "info", "debug", "trace"

cameras:
  - name: "camera1"
    device_name: "AMC108EF91BA102126"
    ip: "192.168.1.91"
    username: "admin"
    mac_address: "A0:60:32:05:E1:7C"
    # Password should be set via environment variable: CAMERA1_PASSWORD

  - name: "camera2"
    device_name: "AMC10802AF9B53A9D5"
    ip: "192.168.1.92"
    username: "admin"
    mac_address: "A0:60:32:04:E4:D2"
    # Password should be set via environment variable: CAMERA2_PASSWORD

  - name: "camera3"
    device_name: "AMC10858C5C8435EF5"
    ip: "192.168.1.93"
    username: "admin"
    mac_address: "A0:60:32:04:E7:6A"
    # Password should be set via environment variable: CAMERA3_PASSWORD

  - name: "camera4"
    device_name: "AMC108D0D9673DEA55"
    ip: "192.168.1.94"
    username: "admin"
    mac_address: "A0:60:32:04:EB:27"
    # Password should be set via environment variable: CAMERA4_PASSWORD

  - name: "camera5"
    device_name: "AMC108A416274B2DA7"
    ip: "192.168.1.95"
    username: "admin"
    mac_address: "A0:60:32:05:DF:C9"
    # Password should be set via environment variable: CAMERA5_PASSWORD